# Generated by Django 3.0 on 2020-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200706_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='user_profile.Hashtag'),
        ),
    ]
