# Generated by Django 3.0 on 2020-07-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20200709_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='header_img',
            field=models.ImageField(blank=True, default='/default-images/default-header-img.png', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, default='/default-images/default-profile-img.png', null=True, upload_to='media'),
        ),
    ]
